linuxdeepin/dde-calendar

CMakeLists.txt
calendar-client/CMakeLists.txt
calendar-service/CMakeLists.txt
schedule-plugin/CMakeLists.txt

Log: use GNUInstallDirs in CmakeLists
https://github.com/linuxdeepin/developer-center/issues/3167

chore: use GNUInstallDirs in CmakeLists

---

README.md
README.zh_CN.md
debian/dde-calendar.1

reuse合规性检查修改
Log: reuse合规性检查修改

fix: reuse合规性检查修改

---

calendar-client/CMakeLists.txt
calendar-service/CMakeLists.txt
schedule-plugin/CMakeLists.txt
tests/dde-calendar-client-test/CMakeLists.txt
tests/dde-calendar-service-test/CMakeLists.txt

Correct a typo in CMakeLists.txt

chore: correct a typo in CMakeLists.txt

---

calendar-client/assets/dde-calendar/calendar/en_US/calendar.md
calendar-client/assets/dde-calendar/calendar/zh_CN/calendar.md
calendar-client/assets/dde-calendar/calendar/zh_HK/calendar.md
calendar-client/assets/dde-calendar/calendar/zh_TW/calendar.md

社区版系统不支持日历的云同步功能,需要在帮助手册中声名
Log: 补充帮助手册内容
Issue: linuxdeepin/developer-center#3804

feat: deepin system does not support calendar sync

---

3rdparty/kcalendarcore/CMakeLists.txt
DDav/CMakeLists.txt
calendar-client/CMakeLists.txt
calendar-common/CMakeLists.txt
calendar-service/CMakeLists.txt
schedule-plugin/CMakeLists.txt
tests/cmake/asan.cmake

Log: https://github.com/linuxdeepin/developer-center/issues/4292

fix: remove illegal gcc option

---

CMakeLists.txt
calendar-client/CMakeLists.txt
calendar-client/assets/dbus/com.deepin.Calendar.service.in
calendar-service/CMakeLists.txt
calendar-service/assets/data/com.deepin.dataserver.Calendar.service.in
calendar-service/src/dbmanager/dhuanglidatabase.cpp
calendar-service/src/main.cpp
calendar-service/src/synchronization/syncoperation.h
linglong.yaml

Log:
1. search for data files in XDG_DATA_DIRS
2. use cmake option to set path in dbus service

feat: avoid use hardcode path

---

.clang-format
calendar-client/src/customWidget/jobtypelistview.cpp
calendar-client/src/customWidget/jobtypelistview.h
calendar-client/src/dataManage/accountitem.cpp
calendar-client/src/dataManage/accountitem.h
calendar-client/src/dbus/dbusaccountrequest.cpp
calendar-client/src/dbus/dbusaccountrequest.h
calendar-client/src/dialog/scheduletypeeditdlg.cpp
calendar-client/src/dialog/scheduletypeeditdlg.h
calendar-client/src/dialog/settingdialog.cpp
calendar-client/src/dialog/settingdialog.h
calendar-service/src/calendarDataManager/daccountmodule.cpp
calendar-service/src/calendarDataManager/daccountmodule.h
calendar-service/src/dbusservice/daccountservice.cpp
calendar-service/src/dbusservice/daccountservice.h

支持导入ics文件,ics是通用日历格式
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/5018

feat: support for import ics file

---

calendar-client/assets/dde-calendar/calendar/en_US/calendar.md

chore: correct typos in en_US docs

---

calendar-service/src/calendarDataManager/daccountmanagemodule.cpp

由于日志同步功能在社区版本还不可用
在社区版系统隐藏账户登陆
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/5912

feat: hide account login in community version

---

calendar-client/src/dbus/dbushuanglirequest.cpp
calendar-common/src/huangliData/lunardatastruct.h
calendar-service/assets/holiday-cn/2024.json
calendar-service/assets/resources.qrc
calendar-service/src/dbmanager/dhuanglidatabase.cpp

feat: Supplement the holidays for the year 2024

---

calendar-service/assets/holiday-cn/2023.json
calendar-service/assets/resources.qrc
calendar-service/src/calendarhuangli.cpp
calendar-service/src/calendarhuangli.h
calendar-service/src/dbmanager/dhuanglidatabase.cpp
calendar-service/src/dbmanager/dhuanglidatabase.h
calendar-service/src/dbusservice/dhuangliservice.cpp
debian/changelog

优化查询节假日返回类型为QJsonArray, 提高代码可读性,便于调用者处理

feat: Optimize holiday query, change the return type to QJsonArray 

---

calendar-client/src/dbus/doanetworkdbus.h
calendar-service/src/calendarDataManager/daccountmanagemodule.cpp
calendar-service/src/synchronization/syncfilemanage.cpp
calendar-service/src/synchronization/syncoperation.cpp

feat: enable cloud sync

---

calendar-service/src/csystemdtimercontrol.cpp
debian/changelog
debian/dde-calendar.postinst

fix: install deb package error

---

calendar-client/src/customWidget/scheduleRemindWidget.cpp
calendar-client/src/widget/monthWidget/monthview.cpp
calendar-client/src/widget/yearWidget/yearscheduleview.cpp
calendar-client/src/widget/yearWidget/yearwindow.cpp

由于dtk版本更新,新版本的悬浮框会导致主窗口失活
改用widget模式显示悬浮框
Log:

fix: problem of not displaying the floating frame

---

calendar-service/src/dbus/dunioniddbus.cpp
debian/changelog

fix: cloud sync dbus error

---

calendar-client/assets/dbus/com.deepin.Calendar.service.in
calendar-service/CMakeLists.txt
calendar-service/assets/data/dde-calendar.service.in

use systemd service instead of dbus activate
Issue: https://github.com/linuxdeepin/developer-center/issues/9742

chore: dbus activation adapt to AM

---

.tx/transifex.yaml

chore: update transifex config

---

arm64/linglong.yaml
debian/changelog
linglong.yaml

update changelog
Log: update changelog

chore: update changelog

---

arm64/linglong.yaml
debian/changelog
linglong.yaml

Bump version to 5.14.11
Log: Bump version to 5.14.11

chore: Bump version to 5.14.11

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 5.14.13
Log: Bump version to 5.14.13

chore: Bump version to 5.14.13

---

README.md
README.zh_CN.md

remove invalid  url
Log: remove invalid  url

fix: remove invalid  url

---

calendar-client/assets/builtin/icons/dde_calendar_ban_32px.svg
calendar-client/assets/builtin/icons/dde_calendar_ji_32px.svg
calendar-client/assets/builtin/icons/dde_calendar_xiu.svg
calendar-client/assets/builtin/icons/dde_calendar_yi_32px.svg
calendar-client/assets/resources/builtin/icons/dde_calendar_ban_32px.svg
calendar-client/assets/resources/builtin/icons/dde_calendar_ji_32px.svg
calendar-client/assets/resources/builtin/icons/dde_calendar_xiu.svg
calendar-client/assets/resources/builtin/icons/dde_calendar_yi_32px.svg
calendar-client/src/scheduleTask/cscheduleoperation.cpp
calendar-client/src/view/graphicsItem/cmonthdayitem.cpp
calendar-client/src/view/graphicsItem/cmonthscheduleitem.cpp
calendar-client/src/widget/dayWidget/dayhuangliview.cpp

The svg files include font-family cause that do not show the font, use QIcon replace DIcon in order to fix image non-clear issue.
Log: Fix some UI issues.
Bug: https://pms.uniontech.com/bug-view-304001.html
https://pms.uniontech.com/bug-view-303131.html
https://pms.uniontech.com/bug-view-298283.html

fix: Fix some UI issues

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Bump version to 6.5.4
Log: Bump version to 6.5.4

chore: Bump version to 6.5.4

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml
translations/dde-calendar_lo.ts

fix: update translations of lo
