linuxdeepin/dde-calendar

.packit.yaml
rpm/deepin-calendar.spec

This commit contains the specfile for building the official package for Fedora
with a Packit setup.
Ultimately, a unified specfile is targeted for Fedora and any other rpm-based
distributions, e.g. openEuler.
And Packit(https://packit.dev/) is a tool for maintaining specfile within
upstream source. It requires a simple config file(.packit.yaml).
Log:
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>

feat: Initial packit setup

---

assets/dde-calendar.desktop

Fixes: desktop-entry-lacks-keywords-entry lintian error.

Add Keywords in dde-calendar.desktop file.

---

tests/third-party_stub/stub.h

Fixes: https://github.com/linuxdeepin/developer-center/issues/2387
'uint32_t' defined in:

tests: add missing header

---

calendar-service/src/dbusservice/dhuangliservice.cpp
debian/changelog

移除黄历接口对调用者的检查
这些接口没必要限制外部调用
控制中心需要使用黄历接口获取节假日
Log:

feat: Remove caller checks for Huangli dbus interface

---

README.md
README.zh_CN.md
calendar-client/CMakeLists.txt
debian/control
rpm/dde-calendar.spec
schedule-plugin/CMakeLists.txt
tests/dde-calendar-client-test/CMakeLists.txt

fix: remove unused dframeworkdbus

---

calendar-client/src/dbus/dbushuanglirequest.cpp
calendar-common/src/huangliData/lunardatastruct.h
calendar-service/src/dbusservice/dhuangliservice.cpp
debian/changelog
debian/rules

将 [chore: deepin system does not support calendar sync](https://github.com/linuxdeepin/dde-calendar/pull/146/commits/a297ad6668285a44f7e3471ebe0a033129964761) 合并到主线，这个提交之前是基于 5.10.1 更改的，用于修复专业版上的问题
dde-daemon会使用getFestivalMonth接口的数据配置自动关机, 需要保持接口兼容性，所以恢复了之前接口返回值结构变化

feat: keep the json struct of getFestivalMonth

---

calendar-client/CMakeLists.txt
calendar-client/assets/org.deepin.calendar.metainfo.xml

feat: add metainfo of dde

---

calendar-common/src/units.cpp
calendar-common/src/units.h
calendar-service/src/calendarDataManager/daccountmanagemodule.cpp
calendar-service/src/calendarDataManager/daccountmanagemodule.h
calendar-service/src/dbmanager/dhuanglidatabase.cpp
calendar-service/src/dbmanager/dhuanglidatabase.h

feat: auto update holiday data

---

calendar-common/src/dbustimedate.cpp
calendar-common/src/dbustimedate.h
calendar-service/src/calendarDataManager/daccountmanagemodule.cpp
calendar-service/src/calendarDataManager/daccountmanagemodule.h

feat: get system setting from dbus

---

debian/changelog

在社区版启动云同步
在线定时更新节假日数据
通用设置支持跟随系统配置
Log:

chore: Release 5.13.0

---

calendar-service/assets/data/com.dde.calendarserver.calendar.timer
debian/changelog

feat: Delayed start of service

---

calendar-client/src/dialog/schedulectrldlg.cpp
debian/changelog

日历在日程右键删除时, 弹出的确认对话框会显示在左上角
目前推测是窗管的问题, 先在应用层的临时解决
Issues: https://github.com/linuxdeepin/developer-center/issues/10141

fix: dialog window display position error

---

calendar-service/src/csystemdtimercontrol.cpp
debian/changelog

玲珑环境会将家目录config进行隔离, 无法在此创建systemd服务
检测玲珑环境并修正config路径位置
Log:

feat: Unable to set timer reminder in Linglong environment

---

calendar-client/src/widget/monthWidget/monthview.cpp
calendar-client/src/widget/sidebarWidget/sidebarcalendarwidget.cpp
calendar-client/src/widget/yearWidget/yearwindow.cpp
calendar-service/src/alarmManager/dalarmmanager.cpp
calendar-service/src/csystemdtimercontrol.cpp
debian/changelog

* fix: sidebar calendar widget(Issue: https://github.com/linuxdeepin/developer-center/issues/10343)
* feat: Execute reload after changing systemd(Issue: https://github.com/linuxdeepin/developer-center/issues/10093)
* fix: remind widget display position(Issue: https://github.com/linuxdeepin/developer-center/issues/10341)

chore: Release 1.5.5

---

calendar-client/src/customWidget/cweekwidget.cpp
debian/changelog

cweekwidget组件使用locale.toString替换tr手动翻译
一来可以使用qt自己的翻译支持的语言更广泛, 且能减少翻译工作量
二来避免翻译人员在不知道显示场景下使用长翻译而不是缩写
Bug: https://pms.uniontech.com/bug-view-271483.html

feat: cweekwidget uses locale to replace tr

---

calendar-service/assets/data/com.dde.calendarserver.calendar.service

Because of the linglong launch up very slowing when first time, then the timer send dbus to launcher calendar service will timeout(25s). In fact，it does not need to wait reply.
Log: Workaround service send dbus reply timeout issue.
Bug: https://pms.uniontech.com/bug-view-292535.html

fix: Workaround service send bus reply timeout issue

---

README.md
README.zh_CN.md

用户文档的链接无法在外部使用, 并且是错误的地址, 暂时先删除

chore: remove user documentation from README

---

calendar-client/config/dbus/ControlCenterAdaptor.cpp
calendar-client/config/dbus/ControlCenterAdaptor.h

Add DBus adaptor class for org.deepin.dde.ControlCenter1 interface
Log: add ControlCenter DBus adaptor

chore: add ControlCenter DBus adaptor

---

CMakeLists.txt

As title.
Log: Fix missing translation files.

fix: missing translation files

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Update the linglong base to 25.0.0 and v5.14.14 release.
Log:  v5.14.14 release.

chore: [tag]New tag v5.14.14

---

arm64/linglong.yaml
debian/changelog
linglong.yaml
loong64/linglong.yaml

Update the linglong base to 25.0.0 and v6.5.2 release.
Log: v6.5.2 release.

chore: [tag]New tag v6.5.2

---

calendar-common/src/dschedule.cpp

The normal multidays schedules are ignored.
Log: Fix can not create multidays schedule issue.
Bug: https://pms.uniontech.com/bug-view-304011.html

fix: Fix can not create multidays schedule issue

---

arm64/linglong.yaml
linglong.yaml
loong64/linglong.yaml

- Changed package source URLs from the old CI server to the new local server for amd64, arm64, and loong64 architectures.
- Ensured that all relevant package URLs are updated to maintain consistency across different architectures.
Log: Update package sources to point to the new server for better accessibility and reliability.

chore: Update package sources in linglong.yaml files
